Odin Project: Associations
kwizl/private-events pull request #3
Opened 2020-05-06 18:09 UTC by kwizl

# Private Events Project

- This project entails making a web application with the basic functionality of the Eventbrite web application. A user registers, then they have the authorization to login to the web app. They can create events an also view the events created by other users.

2020-05-07 15:22 UTC, Ispirett requested changes
## Status Changes Required
Firstly Great job so far on this project you doing well @kwizl  @abdelp. :+1: 
There are just a few issues to take care of.

- [x] There should be a link to take you too the events show page.
- [x] I can't seem to get myself added to an event.
- [x] Upcoming events and past events do not seem to be working correctly. When I add events it never shows up in either.

2020-05-07 22:30 UTC, abdelp commented
the upcoming and past events show up when a user pushes the "Assist" button

2020-05-08 22:06 UTC, wathigo requested changes
### Changes Required
Great work so far team :clap: 

**REQUIRED**
* There is an error when I press assist button. Check this out :point_down: 
![Screenshot from 2020-05-09 00-51-22](https://user-images.githubusercontent.com/44072711/81452722-3f355780-9190-11ea-9eb9-aec9b587301b.png)
* Helper methods for the controllers should be placed in the `ApplicationController`. Only views related logic should reside in `app/helpers`.  For example `assist_event` method in `app/helpers` coud be moved to the application controller. **Resources**:
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

**After implementing the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

2020-05-10 22:45 UTC, uryelah requested changes
Hello **Abdel Pérez Téllez & Martin Njoroge**, I'm Sarah, your reviewer for this PR 👩‍🚀  

Good job with this project! The interface looks nice and it seems like all the functionality is mostly there. 

There are still some issues to fix with your code organization and small requirements from Odin project, [make sure to read the link and comment from the last TSE reviewer](http://codefol.io/posts/Where-Do-I-Put-My-Code/), check the comments below 🦾 

--------

## Changes Required 🏗️ 🐛 💡

2020-05-10 22:45 UTC, uryelah commented on app/controllers/events_controller.rb
> +    @events = Event.select('events.*, users.id user_id, users.name creator_name').joins(:creator)
The EventsController#index:

- [ ] lists past events, i.e. @past_events = Event.previous_events

- [ ] lists ucomping events, i.e. @upcoming_events = Event.upcoming_events

2020-05-10 22:45 UTC, uryelah commented on app/controllers/users_controller.rb
> +  def show
The UsersController#show:

- [ ] lists events created by user, i.e. @created_events =  current_user.events

2020-05-10 22:45 UTC, uryelah commented on app/helpers/events_helper.rb
> +  def event_params
- [ ] If a method is only needed in the controller it should be a private method in its controller.
The methods in the helpers are the ones you need to access in the views and should not connect directly to model methods. EX(Post.new, Comment.create, current_user.friends.find_by(...)...)

- Check the link in the previous review about where you should put your code in rails to keep the project tidy.

2020-05-10 22:45 UTC, uryelah commented on app/helpers/user_helper.rb
> +  def user_params
- [ ] This method should be a private method inside UsersController

2020-05-10 22:45 UTC, uryelah commented on app/views/events/index.html.erb
> +    <% @events.each do |e| %>
- [ ] There should be no logic at all( if else, each, etc) in the views.
View logic should be inside the pertinent helper.

2020-05-10 22:45 UTC, uryelah commented on app/views/events/show.html.erb
> +  <% @attendees.each do |a| %>
- [ ] There should be no logic at all( if else, each, etc) in the views.
View logic should be inside the pertinent helper.

2020-05-10 22:45 UTC, uryelah commented on app/views/users/show.html.erb
> +    <% @upcoming_events.each do |e| %>
- [ ] There should be no logic at all( if else, each, etc) in the views.
View logic should be inside the pertinent helper.

2020-05-10 22:46 UTC, uryelah commented
**Kindly fix the pointed out issues before requesting the next code review**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-05-12 02:02 UTC, uryelah commented
Good job with most of the changes guys!

You still need to take the logic out of the views and into the helpers though.

[Maybe this StackOverflow thread can give you some direction.](https://stackoverflow.com/questions/53130326/rails-return-html-from-helper-method)
--------

## Changes Required 🏗️ 🐛 💡

- [ ] Remove any logic from the views.

2020-05-12 20:29 UTC, mosesogwo approved these changes
**Great! Project is approved.**

_**Good luck in your next project**_

### Status: Approved :heavy_check_mark:

2020-05-12 20:55 UTC, merged